name: Update Blacklist

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download blacklist
        run: curl -L -o blacklist.txt https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add blacklist.txt
          git commit -m 'Update blacklist.txt'
          git push